### ISSUE TITLE
fix: タブレット画面でアプリについての説明カードのスタイルが崩れる

### ISSUE THREAD

**Issue by shiron4710** [after-school-garbage-squad/repaint-LP#46]
flexが`space-between`なのでスマホで見た時に要素が離れて見えます。
これを許容するのなら閉じてもらって構いません

<img width="861" alt="スクリーンショット 2023-07-14 0 28 39" src="https://github.com/after-school-garbage-squad/repaint-LP/assets/54439127/3fd9264d-e73c-4db9-9631-5dc1e963a8b0">

**Comment by Bayathy** [comment]
あ、そこタブレット画面で見るの忘れてました直します
